version: "3.7"

services:
  terraform-env:
    container_name: terraform-environment
    image: terraform-env
    environment:
      - PASSWORD=password
      - PORT=8443
    ports:
      - 8443:8443
      - 9090:80
    volumes:
      - environment_persistent:/root

volumes:
  environment_persistent: